language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 1

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update

script:
  - composer run-script phplint
  - vendor/bin/phpunit --coverage-text
